


OPENAI_API_KEY = 'something'
OPENA_API_KEY = 'sk-zGWGr9Ff-6qyX5hb9t82sI6LQ9RyQHRMCfhWhHu91GT3BlbkFJQIPtg66sYukuPW9GQ09cCL2rn8_t_21BQTUdQ7hn4A'
BUCKET_NAME = 'bigdatadamg7245'
S3_FILE_KEY = 'metadata.jsonl'
S3_ROLE = 'Deepak_admin'
S3_ACCESS_KEY = 'AKIAZI2LIWOWP7ACGSWH'